Could com.example:spring-rabbit-global-errorhandler:2.3.10 drop off redundant dependencies to loose weight?
spring-projects/spring-amqp-samples pull request #65
Opened 2021-08-05 02:32 UTC by Celebrate-future

Hi, I am a user of project **_com.example:spring-rabbit-global-errorhandler:2.3.10_**. I found that its pom file introduced **_58_** dependencies. However, among them, **_7_** libraries (**_12%_**) have not been used by your project (the redundant dependencies are listed below). Reduce these useless dependencies can help prevent conflicts between library versions. MeanWhile, it can minimize the total added size to projects. It can also help enable advanced scenarios for this project. 
This PR helps **_com.example:spring-rabbit-global-errorhandler:2.3.10_** lose weight :) I have tested the revised configuration in my local environment. It is safe to remove the unused libraries.

Best regards

2021-08-05 02:32 UTC, pivotal-cla commented
@Celebrate-future Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp-samples&pullRequestId=65)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-amqp-samples&pullRequestId=65) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-08-05 02:36 UTC, pivotal-cla commented
@Celebrate-future Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-amqp-samples&pullRequestId=65)!

2021-08-09 16:55 UTC, artembilan requested changes

2021-08-09 16:55 UTC, artembilan commented on spring-rabbit-global-errorhandler/pom.xml
> +   	<dependencyManagement>
Why do we need this explicit management over here?
The `spring-boot-starter-parent` is actual parent for this project and that one already manages all the versions for dependencies we use in this project.
I may find the exclusion for `spring-boot-starter-logging` as a reasonable, but I can't guess the point of this dependency management.
That really was the whole reason to introduce Spring Boot from day first...

Thank you for understanding!

2022-03-14 12:17 UTC, Celebrate-future commented
I have updated the pom file

2024-12-27 16:18 UTC, merged